---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/redirect-entry-point: websecure
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: drikke-org
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: drikke-org
                port:
                  number: 8080
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: whoami-cert
