---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: drikke-org
  name: drikke-org
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: drikke-org
  sessionAffinity: None
  type: ClusterIP
